---
title: "OHI_Visualization"
format: html
editor: visual
---

## Ch 5 of OHI Workshop: Visualization

<http://ohi-science.org/data-science-training/ggplot2.html#plotting-with-ggplot2>

## Running Code

```{r}
library("tidyverse")

```

Load Data

```{r}
#National Parks in California
ca <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/ca.csv") 

#Acadia National Park
acadia <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/acadia.csv")

#Southeast US National Parks
se <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/se.csv")

#2016 Visitation for all Pacific West National Parks
visit_16 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/visit_16.csv")

#All Nationally designated sites in Massachusetts
mass <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/mass.csv")
```

Visualize the Data

```{r}
ggplot(data = ca)+
  geom_point(aes(x = year, y = visitors))
```

```{r}
#to add colors to the graph
ggplot(data = ca) +
    geom_point(aes(x = year, y = visitors, color = park_name))
```

Continuing to better the plot

```{r}
ggplot(data = ca) +
    geom_point(aes(x = year, y = visitors, color = park_name)) +
    labs(x = "Year",
       y = "Visitation",
       title = "California National Park Visitation") +
    theme_bw() +
    theme(legend.title=element_blank())
```

Now Trying for SE instead of CA

```{r}
ggplot(data = se) +
    geom_point(aes(x = year, y = visitors, color = state)) +
    labs(x = "Year",
       y = "Visitation",
       title = "Southeast States National Park Visitation") +
    theme_bw() +
    theme(legend.title=element_blank())+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
